apiVersion: v1
kind: Namespace
metadata:
  name: service-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-habits #Base pod name
  namespace: service-system
spec:
  selector:
    matchLabels:
      app: service-habits #Selector for POD name
  template:
      metadata:
        labels:
          app: service-habits
      spec:
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        terminationGracePeriodSeconds: 60
        containers:
          - name: service-habits
            image: service-habits:1.0
            ports:
              - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-habits
  namespace: service-system
spec:
  type: ClusterIP
  selector:
    app: service-habits
  ports:
    - name: service-habits
      port: 3000
      targetPort: 3000
