apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-habits
  namespace: service-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service-habits #Selector for POD name
  template:
    metadata:
      labels:
        app: service-habits
    spec:
      containers:
        - name: service-habits
          resources:
            limits:
              cpu: 1000m #full CPU core
            requests:
              cpu: 500m #1/2 of CPU core
